### ISSUE TITLE
Having '=' as key separator?

### ISSUE THREAD

**Issue by desertkun** [hjson/hjson-py#10]
I find `=` symbol even more human readable for even simpler JSON alternative.

And the fact that you can skip braces at the root object make it look almost like `*.INI` files, yet with hierarchical functionality.

```
class = content.Medal
components = [
    {
        class = content.components.IconComponent
        icon = medal-tournament-1
        tag = client
    }
    {
        class = content.components.UnlockSoundComponent
        sound = achievement-unlocked-snd
        tag = client
    }
]
description = MEDAL_TOURNAMENT_1_DESC
name = MEDAL_TOURNAMENT_1
```

How can I add `=` as a "alternative", yet allowed key separator? Or at least replace `:` with `=` for my own personal use (I understand that this would break the original JSON compatibility, but for sake of even more convenience, I would like to do that)?

**Comment by laktak** [comment]
Skipping braces at the root level has caused some issues and has been deprecated. You can still use it for now.

If you feel this strongly about `=` vs `:` you could probably create a regex and pipe it through sed before you pass it to the Hjson parser. That way you would not have to maintain your own fork.

**Comment by desertkun** [comment]
I pretty much managed that to work [in my fork](https://github.com/desertkun/hjson-py/commit/6cc6b0e15ec826afd180b390adb4a091dc6604de). If you're the author of the "standard" of the hjson, and would like to allow `=` as optional separator, I would be glad to make a pull request for python implementation.

**Comment by laktak** [comment]
Thanks. Cool that it works for you but I don't see the value in an additional separator.
