### ISSUE TITLE
Default indent behavior of hjson.dumps does not match documentation

### ISSUE THREAD

**Issue by teichert** [hjson/hjson-py#13]
[Documentation](https://raw.githubusercontent.com/hjson/hjson-py/master/hjson/__init__.py) says:

>     If ``indent`` is a string, then JSON array elements and object members
>     will be pretty-printed with a newline followed by that string repeated
>     for each level of nesting. ``None`` (the default) selects the most compact
>     representation without any newlines. 

Note that the default, `ident=None`, should produce a compact string _without any newlines_.

Expected behavior:
```
>>> import hjson
>>> d = dict(a=1, b=2)
>>> hjson.dumps(d)
'{a: 1, b: 2}'
```
Actual behavior:
```
>>> hjson.dumps(d)
'{\n  a: 1\n  b: 2\n}'
```

**Comment by laktak** [comment]
Thanks. The documentation is incorrect - I've updated it.

To support this style of output the python version would need a `condense` option similar to the [JavaScript implementation](https://github.com/hjson/hjson-js).
