### ISSUE TITLE
The `hjson` script is b0rken because it does not use console_scripts

### ISSUE THREAD

**Issue by ztane** [hjson/hjson-py#20]
The [`consle_scripts` of setup.py](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) should be used. 

The `hjson` file in `bin` of the python prefix now says

```#!/bin/sh

python -m hjson.tool "$@"
```

And it won't do, since I didn't install this to Python 2 on my Ubuntu.

**Comment by groodt** [comment]
Fixed in: https://github.com/hjson/hjson-py/pull/31
