### ISSUE TITLE
Bad TypeError message if you pass a non-text, non-bytestring argument to `hjson.loads()`

### ISSUE THREAD

**Issue by alexwlchan** [hjson/hjson-py#6]
Here’s an example of some code I just tried to write with hjson-py:

```python
import hjson
with open('example.json') as f:
    hjson.loads(f)
```

I made a mistake on the third line – I tried to load from `f` rather than the contents of `f`. I should have written `hjson.loads(f.read())` – oh well.

This code quickly throws a TypeError, but the message is confusing:

<pre><code>
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/alexwlchan/.virtualenvs/tempenv-69df265385ab6/lib/python3.5/site-packages/hjson/__init__.py", line 173, in loads
    return _default_decoder.decode(s)
  File "/Users/alexwlchan/.virtualenvs/tempenv-69df265385ab6/lib/python3.5/site-packages/hjson/decoder.py", line 514, in decode
    obj, end = self.raw_decode(s)
  File "/Users/alexwlchan/.virtualenvs/tempenv-69df265385ab6/lib/python3.5/site-packages/hjson/decoder.py", line 536, in raw_decode
    raise TypeError("Input string must be text, not bytes")
<strong>TypeError: Input string must be text, not bytes</strong>
</code></pre>

Why is it complaining about bytes? I didn’t pass it any bytes – I passed it a file object. You get the same message if you try `hjson.loads(0)` or `hjson.loads(None)` or `hjson.loads(object)`. All saying "not bytes" when I‘m already passing values that aren’t bytes.

This error message should be corrected either:

* To only say "not bytes" if I actually passed in a bytestring, or
* To say "not _&lt;type>_" based on the type of the value I passed in.

---

**Setup:**

```console
$ hjson --version
Hjson 2.0.2

$ python --version
Python 3.5.2

$ cat example.json
// This is a comment
{"foo": "bar"}
```

**Comment by laktak** [comment]
Thanks and sorry for the late reply (must have missed the notification).
